name: DEV
on:
  pull_request:
    types: [opened, edited, closed]
    
    
jobs:

  restore:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Configuração do Dotnet
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: 6.0.x
       
      - name: Publicação do pacote
        uses: Nuget/setup-nuget@v1.1.1

      - name: Restauração do pacote
        run: dotnet restore ./src

  build:
    needs: restore
    runs-on: ubuntu-latest
    
    steps:
      - name: Build do pacote
        run: dotnet build ./src --no-restore

  testes:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Testes de unidade
        run: dotnet test ./src --no-build --verbosity normal

  sonarQube:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SonarCloud Scan 
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
        
